### ISSUE TITLE
v 10.0.0 --devs does not trigger collection of devs stats.

### ISSUE THREAD

**Issue by grimsquirrel** [src-d/hercules#266] opened 2019-04-02 15:42 UTC
hercules --devs d:\localrepo\ngc | labours -m all >> output text file

v10.0.0  when switch --devs used, labours complains devs stats were not collected.  when i replace v10.0.0 herc executable with v8.3.2, labours process output correctly.
[output_v8.3.2.txt](https://github.com/src-d/hercules/files/3034776/output_v8.3.2.txt)
[output_v10.0.0.txt](https://github.com/src-d/hercules/files/3034777/output_v10.0.0.txt)

**Comment by vmarkovtsev** [comment] 2019-04-02 17:21
Hi @grimsquirrel, I think that this is a duplicate of #265 
Workaround: use `--pb`.

**Closed by vmarkovtsev** 2019-04-02 17:21 UTC
